### ISSUE TITLE
The specified device interface or feature level is not supported on this system.

### ISSUE THREAD

**Issue by BalenDanny** [RobyDX/SharpDX_D3D12HelloWorld#3]
@RobyDX 

I am getting this error, i am pretty new to directx, tho i am pretty good at c#.

``` javascript

An unhandled exception of type 'SharpDX.SharpDXException' occurred in SharpDX.dll

Additional information: HRESULT: [0x887A0004], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_UNSUPPORTED/Unsupported], Message: The specified device interface or feature level is not supported on this system.

```

What i understand from this is that my machine can't support directx 11 tho my amd graphics card does, i debugged a bit and found out that since i am using switchable graphics laptop, it picked up my intel and not amd.

How can i fix this, thanks for the tutorial btw.

If i may ask one more thing, how did you this, like how you created this how you found out you do this and this and this like that and how to convert from c++ to c#, i know c++ too btw.

**Comment by BalenDanny** [comment]
Edit:

I have changed the start of  using (factory) in LoadPipeLine()  to:

``` csharp
using (var factory = new Factory4())
            {
                Adapter adapter = factory.GetAdapter(1);

                device = new Device(adapter, SharpDX.Direct3D.FeatureLevel.Level_11_0);
[...]
```

I now get a error at: 

``` csharp
SwapChain tmp = new SwapChain(factory, device, sdscp);

```

and the error is:

``` javascript


An unhandled exception of type 'SharpDX.SharpDXException' occurred in SharpDX.dll

Additional information: HRESULT: [0x887A0001], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_INVALID_CALL/InvalidCall], Message: The application made a call that is invalid. Either the parameters of the call or the state of some object was incorrect.

Enable the D3D debug layer in order to see details via debug messages.

```

I debugged a bit more and the adapter is still not my amd gpu, 

Description = "Microsoft Basic Render Driver\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"

**Comment by BalenDanny** [comment]
Edit 2:

The Adapter luid is like this:

AdapterLuid = 'device.AdapterLuid' threw an exception of type 'System.AccessViolationException'

weird....

It is reading a wrong memory location....

This made me think into that the index for the adapter is wrong, but i have switchable graphics and it says it in my laptop and device manager + i have driver for both :+1:

**Comment by BalenDanny** [comment]
I have checked dxdiag and the system supports directx 11.1

**Comment by RobyDX** [comment]
Are you using Windows 10? Anyway check last version updated to SharpDx 3.0
